apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: proxapeople-production
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 160
      timeoutSeconds: 600
      serviceAccountName: 673103558160-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/proxapeople-production/proxapeople:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        - name: AUTH0_DOMAIN
          value: dev-45snae82elh3j648.us.auth0.com
        - name: AUTH0_CLIENT_ID
          value: 3ylhlRL1bujy8Df92FcaHlhmoJ7jQYjV
        - name: AUTH0_AUDIENCE
          value: https://api.proxapeople.com
        - name: FRONTEND_URL
          value: https://proxapeople-production-fnenzqaojq-uc.a.run.app
        - name: CORS_ORIGIN
          value: https://proxapeople-production-fnenzqaojq-uc.a.run.app
        - name: JWT_EXPIRES_IN
          value: 1h
        - name: JWT_REFRESH_EXPIRES_IN
          value: 7d
        - name: BCRYPT_ROUNDS
          value: "12"
        - name: RATE_LIMIT_WINDOW_MS
          value: "900000"
        - name: RATE_LIMIT_MAX_REQUESTS
          value: "100"
        - name: CORS_CREDENTIALS
          value: "true"
        - name: SESSION_MAX_AGE
          value: "86400000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: database-url-production
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: jwt-secret-production
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: auth0-client-secret-production
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: session-secret-production
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 10
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 4
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3